[formatting]
align_entries  = true
column_width   = 200
reorder_arrays = true

# The CI builds exclude these explicitly. Having them here makes it easier to
# format everything we care about. 
#
# ```
# taplo format .
# ```
