[package]
name = "gcloud_sdk_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic-prost-build = { version = "0.14.2" }
prost-build = "0.14.1"
prettyplease = "0.2"
syn = { version = "2", default-features = false, features = [
  "full",
  "parsing",
] }
